apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    crossplane.io/name: example-instance
    crossplane.io/managed: "true"
  name: example-instance
spec:
  forProvider:
    ami: ami-0dee22c13ea7a9a67
    instanceType: t2.micro
    subnetIdSelector:
      matchLabels:
        crossplane.io/name: example-subnet
    region: ap-south-1
  providerConfigRef:
    name: default